name: markdownlint

on: [push]

jobs:
  delivery:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run markdownlint
        uses: actionshub/markdownlint@master
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.mlc_config.json'
